export ZSH="/home/{{ user }}/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git docker node postgres ansible golang vscode)
source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH

# gitlab setup
# GITLAB_TOKEN needs to be set up separately
export GITLAB_USERNAME={{ gitlab_username }}
export GITLAB_TOKEN={{ gitlab_token }}
export GOPRIVATE=gitlab.com/guiding-lands

# Docker
export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1

# ibus stuff
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

export LANG=en_US.UTF-8
